### ISSUE TITLE
Question about multi-GPU training

### ISSUE THREAD

**Issue by YunzeMan** [SilongYong/SQA3D#3]
Hi, I was wondering if your codebase support multi-GPU training and if so, how to enable it? Thanks.

**Comment by jeasinema** [comment]
@SilongYong

**Comment by SilongYong** [comment]
Hi @YunzeMan, thanks for your interest in our research! The codebase provided cannot support multi-GPU training for the computational cost could be handled by a single GPU. However, the format of our codebase is similar to Pytorch-lightning, you can slightly modify the file ```solver.py``` into lightning format and the lib can support multi-GPU training using just a single line.
