### ISSUE TITLE
details about the SQA3D Localization task

### ISSUE THREAD

**Issue by Daniellli** [SilongYong/SQA3D#4]
thank you for your such novel work,  

could i ask more details about the  results on [PwD](https://paperswithcode.com/sota/referring-expression-on-sqa3d-1). Namely,  what does the "random" mean ?   or how to generate the such localization result ? 

again, apperciate.

**Comment by jeasinema** [comment]
Thanks for your interest in our dataset.

Below is how we produce the "random" result. Basically, we randomly generate a 2D location and a rotation between -pi~pi.

Let me know if you have further questions.

https://github.com/SilongYong/SQA3D/blob/3abb2c5f879de3273588b8ee4227283b0c60e350/utils/localization_metric.py#L65-L76
