### ISSUE TITLE
Splitting Evaluation for "What," "Is," "How," "Can," "Which," and "Others" Sub-Questions

### ISSUE THREAD

**Issue by YunzeMan** [SilongYong/SQA3D#5]
Hi, I noticed that in Table 3 of your paper, you've divided the evaluation into several subsets of questions. I'm curious if you have any corresponding scripts to perform this task. The current codebase appears to only report the overall EM@1 and EM@10 metrics.

**Comment by jeasinema** [comment]
@SilongYong
